services:
  ui:
    stdin_open: true #???
    ports:
      - "3000:3000"
    build:
      context: ./ui
      dockerfile: Dockerfile
    networks:
      - vocal-studio

networks:
  vocal-studio:
    driver: bridge
